### ISSUE TITLE
Check Project 2 Submission

### ISSUE THREAD

**Issue by Shaileh** [jce-il/project-template#4]
Todo: delete all unnecessary items, add suitable labels (with priotity and estimation), milestone, assignee, etc.
#### Related Issues/Tasks
- [ ] #1
- [ ] #2

#### Scenario (test)
- [ ] Step 1
- [ ] ...
- [ ] Expected result

## User Story Template
- As a ...
- I want ...
- So that ...

#### Checklist, e.g.,:
- [ ] Feature scenarios/tests passing
- [ ] Iteration page updated, including:
  - [ ] Iteration retrospective
  - [ ] Code reviewes
  - [ ] Client review
  - [ ] Issues updates
  - [ ] Section on application of course materials
- [ ] git tag
- [ ] Next iteration:
  - [ ] Open page
  - [ ] Select stories and plan issues
  - [ ] Test scenarios
- [ ] All engineers filled peer-review 
- [ ] Submitted
  - [ ] Announcement in chat room
  - [ ] Assign this issue to checker
  - [ ] Register for a review meeting

**Comment by robi-y** [comment]
@Shaileh wrong repository, you open the issue in your new instance!
